# Generated by Django 4.1.1 on 2022-10-06 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_finado', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField()),
                ('imagen', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del Genero', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=32)),
                ('resumen', models.TextField(help_text='Sinopsis de Pelicula', max_length=100)),
                ('duracion', models.PositiveIntegerField()),
                ('imagen', models.URLField(null=True)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.director')),
                ('genero', models.ManyToManyField(to='peliculas.genero')),
            ],
        ),
    ]
