# Generated by Django 4.1.1 on 2022-09-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_director_pelicula_peliculaid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='isbn',
        ),
    ]
