name: Docker Image CI

on:
  push:
    branches: [ "deploy-spring" ]
  pull_request:
    branches: [ "deploy-spring" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag deploy-spring
